services:
  meyer-pc-website:
    image: snooops/meyer-pc-website:29d5269
    restart: unless-stopped
    labels:
      traefik.enable: true
      
      traefik.http.middlewares.meyer-pc-website-https-redirect.redirectscheme.scheme: https
      
      traefik.http.routers.meyer-pc-website.entrypoints: http
      traefik.http.routers.meyer-pc-website.rule: Host(`meyer-pc.de`) || Host(`www.meyer-pc.de`)
      traefik.http.routers.meyer-pc-website.middlewares: meyer-pc-website-https-redirect
      

      traefik.http.routers.meyer-pc-website-secure.entrypoints: https
      traefik.http.routers.meyer-pc-website-secure.rule: Host(`meyer-pc.de`) || Host(`www.meyer-pc.de`)
      traefik.http.routers.meyer-pc-website-secure.tls: true
      traefik.http.routers.meyer-pc-website-secure.tls.certresolver: http
      traefik.http.routers.meyer-pc-website-secure.service: meyer-pc-website
      traefik.http.routers.meyer-pc-website-secure.middlewares: secHeaders@file
      traefik.http.services.meyer-pc-website.loadbalancer.server.port: 3000
      traefik.docker.network: proxy
    networks:
      - proxy
    ports:
      - "3000:3000"

networks:
  proxy:
    external: true
