name: Deploy docker compose
on:
  push: 

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Trigger portainer deployment        
        run: bash scripts/call-portainer-webhook.sh
        env:
          PORTAINER_WEBHOOK: ${{ secrets.PORTAINER_WEBHOOK }}